apprise:
  enabled: true
  notify:
    incomplete-activity: true
    uncaught-exception: true
    login-code: true
  summary: 'ALWAYS'
  urls:
  - ""

browser:
  geolocation: 'US'
  language: 'en'
  visible: false
  proxy: null

activities:
  ignore:
    - 'Get 50 entries plus 1000 points!'
    - "Safeguard your family's info"
  search:
    'Black Friday shopping': 'black friday deals'
    'Discover open job roles': 'jobs at microsoft'
    'Expand your vocabulary': 'define demure'
    'Find places to stay': 'hotels rome italy'
    'Find somewhere new to explore': 'directions to new york'
    'Gaming time': 'vampire survivors video game'
    'Get your shopping done faster': 'new iphone'
    'Houses near you': 'apartments manhattan'
    "How's the economy?": 'sp 500'
    'Learn to cook a new recipe': 'how cook pierogi'
    "Let's watch that movie again!": 'aliens movie'
    'Plan a quick getaway': 'flights nyc to paris'
    'Prepare for the weather': 'weather tomorrow'
    'Quickly convert your money': 'convert 374 usd to yen'
    'Search the lyrics of a song': 'black sabbath supernaut lyrics'
    'Stay on top of the elections': 'election news latest'
    'Too tired to cook tonight?': 'Pizza Hut near me'
    'Translate anything': 'translate pencil sharpener to spanish'
    'What time is it?': 'china time'
    "What's for Thanksgiving dinner?": 'pumpkin pie recipe'
    'Who won?': 'braves score'
    'You can track your package': 'usps tracking'

logging:
  format: '%(asctime)s [%(levelname)s] %(message)s'
  level: 'DEBUG'

retries:
  base_delay_in_seconds: 120
  max: 4
  strategy: 'EXPONENTIAL'

cooldown:
  min: 300
  max: 600

search:
  type: 'both'

accounts:
  - email: ""
    password: ""
